### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by cdrainxv** [team5-microverse/members-only#1]
Hi @polaristlx:

Would you mind taking a look at this repo when you have time?
https://docs.google.com/document/d/1WKR7w5oTy6b31zfSvAI-0aWTEbWqUf-WUOzxei8YP6s/edit

Thanks,

Charles

**Comment by PolarisTLX** [comment]
1. Basic setup:
○ Bcrypt in Gemfile.  
Good.
○ User model with #has_secure_password.  
Good.
○ User object can be created from rails c with something similar to:
User.create(name: "test", email: "abc@mail.com", password: "testtest",
password_confirmation: "testtest").  
This worked once I made the password have 8 characters. So this also shows that you are implementing validations correctly. Great work!
2. Login as user created in console and check if application is working.  
Good.
3. Run tests.    
Were tests required to be written for this project?  They are probably not a big deal, but it will be easier to write them for this very small app to get used to it by the the time you get to your big app and you will be writing a lot of tests.
4. Sessions controller:
○ Login form created
○ Create action checks if user with provided email exists in DB, second to
check if password is correct. 
Good.
○ Sign in/ Sign out links created in application layout.  
Good.
○ Current_user is based on remeber_token kept in cookie.
Good.
○ Current_user method implemented in ApplicationController.
Doesn't seem like it. Not sure how big of a deal this is though.
5. Posts controller:
○ Only new, create and index actions in routes.
Good.
○ New and created actions available only for logged-in user (before_action
filter).
Good.
○ Posts visible for guest users but authors names only for logged-in users (+
test for it).
Good.

Interesting to see the use of HAML instead of ERB.  Overall great job on this guys! :-)  This is a solid foundation for more complex Rails apps. Thumbs up.

**Comment by cdrainxv** [comment]
Thanks @PolarisTLX!
